// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCwEin4bwLXoKmQHGDXWUqq7mZtB-wTmg',
    appId: '1:835730539826:web:5599db454587ae5b63832b',
    messagingSenderId: '835730539826',
    projectId: 'site-track-pro',
    authDomain: 'site-track-pro.firebaseapp.com',
    storageBucket: 'site-track-pro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTsInFyCeSHK3K6Y2Gr0LC09pjlM3tUR0',
    appId: '1:835730539826:android:2e9c1cf7b66de0d363832b',
    messagingSenderId: '835730539826',
    projectId: 'site-track-pro',
    storageBucket: 'site-track-pro.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyDr8kfU9qlUE6EtIMoyQYuKec7q2zSq4',
    appId: '1:835730539826:ios:2f5770cbd5c9d84f63832b',
    messagingSenderId: '835730539826',
    projectId: 'site-track-pro',
    storageBucket: 'site-track-pro.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyDr8kfU9qlUE6EtIMoyQYuKec7q2zSq4',
    appId: '1:835730539826:ios:2f5770cbd5c9d84f63832b',
    messagingSenderId: '835730539826',
    projectId: 'site-track-pro',
    storageBucket: 'site-track-pro.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCwEin4bwLXoKmQHGDXWUqq7mZtB-wTmg',
    appId: '1:835730539826:web:65c36e5aec3986a663832b',
    messagingSenderId: '835730539826',
    projectId: 'site-track-pro',
    authDomain: 'site-track-pro.firebaseapp.com',
    storageBucket: 'site-track-pro.firebasestorage.app',
  );
}
